all tests passing through dockerized, hardhat, proof-chain, ipfs-pinner
Signed-off-by: Pranay Valson <pranay.valson@gmail.com>

diff --git a/docker-compose-ci.yml b/docker-compose-ci.yml
--- a/docker-compose-ci.yml
+++ b/docker-compose-ci.yml
@@ -8,7 +8,6 @@ services:
     restart:  on-failure
     expose:
       - 8545:8545
-      - 8007
     entrypoint: |
       /bin/bash -l -c "
       echo "hardhat-node-address:" $NODE_ETHEREUM_MAINNET
@@ -26,7 +25,6 @@ services:
     container_name: proof-chain
     restart: on-failure
     expose:
-      - 8545:8545
       - 8008
     entrypoint: |
       /bin/bash -l -c "
@@ -34,8 +32,8 @@ services:
       sleep 20;
       echo hard-hat node started!;
       echo "forked-node-address:" $ERIGON_NODE
-      npm run docker:deploy;
-      nc -v rudder 8008;"
+      npm run docker:deploy;"
+      # nc -v rudder 8008;"
     depends_on:
       - eth-node
     networks:
@@ -60,36 +58,37 @@ services:
     ports:
       - 4001:4001
       - 3000:3000
+      - 8080:8080
 
-  rudder:
-    image: "rudder-local:latest"
-    container_name: rudder
-    links:
-      - "ipfs-pinner:ipfs-pinner"
-    # build: 
-    #   context: .
-    #   dockerfile: Dockerfile
-    restart: on-failure
-    depends_on:
-        ipfs-pinner:
-          condition: service_started
-    entrypoint: >
-     /bin/bash -l -c "
-       echo Waiting for proof-chain to be deployed...;
-       while ! nc -v -l -k -p 8008;
-       do
-       sleep 1;
-       done;
-       echo proof-chain contracts deployed!;
-       mix test;"
-      #  exit 0;"
-    environment:
-     - NODE_ETHEREUM_MAINNET=${NODE_ETHEREUM_MAINNET}
-     - BLOCK_RESULT_OPERATOR_PRIVATE_KEY=${BLOCK_RESULT_OPERATOR_PRIVATE_KEY}
-    networks:
-      - cqt-net
-    ports: 
-    - "8080:8080"
+  # rudder:
+  #   image: "rudder-local:latest"
+  #   container_name: rudder
+  #   links:
+  #     - "ipfs-pinner:ipfs-pinner"
+  #   # build: 
+  #   #   context: .
+  #   #   dockerfile: Dockerfile
+  #   restart: on-failure
+  #   depends_on:
+  #       ipfs-pinner:
+  #         condition: service_started
+  #   entrypoint: >
+  #    /bin/bash -l -c "
+  #      echo Waiting for proof-chain to be deployed...;
+  #      while ! nc -v -l -k -p 8008;
+  #      do
+  #      sleep 1;
+  #      done;
+  #      echo proof-chain contracts deployed!;
+  #      mix test;"
+  #     #  exit 0;"
+  #   environment:
+  #    - NODE_ETHEREUM_MAINNET=${NODE_ETHEREUM_MAINNET}
+  #    - BLOCK_RESULT_OPERATOR_PRIVATE_KEY=${BLOCK_RESULT_OPERATOR_PRIVATE_KEY}
+  #   networks:
+  #     - cqt-net
+  #   # ports: 
+  #   # # - "8080:8080"
 
 networks:
   cqt-net:
