add links to ipfs-pinner and proofchain in local test config, set docker to use docker mix config

diff --git a/docker-compose-ci.yml b/docker-compose-ci.yml
--- a/docker-compose-ci.yml
+++ b/docker-compose-ci.yml
@@ -56,43 +56,43 @@ services:
       - "4001:4001"
       - "3000:3000"
 
-  rudder:
-    image: "gcr.io/covalent-project/rudder:latest"
-    container_name: rudder
-    links:
-      - "ipfs-pinner:ipfs-pinner"
-    # build: 
-    #   context: .
-    #   dockerfile: Dockerfile
-    restart: on-failure
-    depends_on:
-      ipfs-pinner:
-        condition: service_started
-    entrypoint: >
-      /bin/bash -l -c "
-        echo "ipfs-node-address:" $IPFS_PINNER_URL;
-        echo "hardhat-node-address:" $NODE_ETHEREUM_MAINNET;
-        echo "brp-op-pk:" $BLOCK_RESULT_OPERATOR_PRIVATE_KEY;
-        echo Waiting for proof-chain to be deployed...;
-        while ! nc -v -l -k -p 8008;
-        do
-        sleep 1;
-        done;
-        echo Proof-chain contracts deployed!;
-        echo Uploading test files to local .ipfs...;
-        curl -F "filedata=@/app/test-data/encoded/1-15892728-replica-0x84a541916d6d3c974b4da961e2f00a082c03a071132f5db27787124597c094c1" http://ipfs-pinner:3000/upload;
-        curl -F "filedata=@/app/test-data/encoded/1-15892755-replica-0x0e7bfa908e3fc04003e00afde7eb31772a012e51e0e094e4add1734da92297f7" http://ipfs-pinner:3000/upload;
-        echo Test bsp files uploaded!;
-        cd /app;
-        mix test --trace --slowest 10;
-        exit 0;"
-    environment:
-      - IPFS_PINNER_URL=${IPFS_PINNER_URL}
-      - NODE_ETHEREUM_MAINNET=${NODE_ETHEREUM_MAINNET}
-      - BLOCK_RESULT_OPERATOR_PRIVATE_KEY=${BLOCK_RESULT_OPERATOR_PRIVATE_KEY}
-      - EVM_EXEC_PATH=${EVM_EXEC_PATH}
-    networks:
-      - cqt-net
+  # rudder:
+  #   image: "gcr.io/covalent-project/rudder:latest"
+  #   container_name: rudder
+  #   links:
+  #     - "ipfs-pinner:ipfs-pinner"
+  #   # build:
+  #   #   context: .
+  #   #   dockerfile: Dockerfile
+  #   restart: on-failure
+  #   depends_on:
+  #     ipfs-pinner:
+  #       condition: service_started
+  #   entrypoint: >
+  #     /bin/bash -l -c "
+  #       echo "ipfs-node-address:" $IPFS_PINNER_URL;
+  #       echo "hardhat-node-address:" $NODE_ETHEREUM_MAINNET;
+  #       echo "brp-op-pk:" $BLOCK_RESULT_OPERATOR_PRIVATE_KEY;
+  #       echo Waiting for proof-chain to be deployed...;
+  #       while ! nc -v -l -k -p 8008;
+  #       do
+  #       sleep 1;
+  #       done;
+  #       echo Proof-chain contracts deployed!;
+  #       echo Uploading test files to local .ipfs...;
+  #       curl -F "filedata=@/app/test-data/encoded/1-15892728-replica-0x84a541916d6d3c974b4da961e2f00a082c03a071132f5db27787124597c094c1" http://ipfs-pinner:3000/upload;
+  #       curl -F "filedata=@/app/test-data/encoded/1-15892755-replica-0x0e7bfa908e3fc04003e00afde7eb31772a012e51e0e094e4add1734da92297f7" http://ipfs-pinner:3000/upload;
+  #       echo Test bsp files uploaded!;
+  #       cd /app;
+  #       MIX_ENV=docker mix test --trace --slowest 10;
+  #       exit 0;"
+  #   environment:
+  #     - IPFS_PINNER_URL=${IPFS_PINNER_URL}
+  #     - NODE_ETHEREUM_MAINNET=${NODE_ETHEREUM_MAINNET}
+  #     - BLOCK_RESULT_OPERATOR_PRIVATE_KEY=${BLOCK_RESULT_OPERATOR_PRIVATE_KEY}
+  #     - EVM_EXEC_PATH=${EVM_EXEC_PATH}
+  #   networks:
+  #     - cqt-net
 
 networks:
   cqt-net:
